let elQuestion1 = prompt("1. **HTML qisqartmasi nima manosi va veb rivojlantirishda ularning bosh maqsadi nima?**")
let elQuestion2 = prompt("HTML-da hiper havolani qanday yaratishingiz mumkin?")
let elQuestion3 = prompt("CSS-da margin va padding orasidagi farqni izohlang.")
let elQuestion4 = prompt("HTML <meta> tegining maqsadi nima?")
let elQuestion5 = prompt("CSS-da elementni horizontal ravishda qanday markazlashishingiz mumkin?")
let elQuestion6 = prompt("Eng kop HTML elementlari uchun standart korsatkich qanday va uni CSS-da qanday ozgartirishingiz mumkin?")
let elQuestion7 = prompt("CSS float xususiyatining maqsadi nima?")
let elQuestion8 = prompt("HTML va CSS-da kodi qanday izohlang?")
let elQuestion9 = prompt("HTML <ul> va <ol> elementlarining maqsadi nima?")
let elQuestion10 = prompt("CSS box modelini va uning qismlarini izohlang.")
alert(elQuestion1 + "  " + elQuestion2 + "  " + elQuestion3 + "  " + elQuestion4 + "  " + elQuestion5 + "  " + elQuestion6 + "  " + elQuestion7 + "  " + elQuestion8 + "  " + elQuestion9 + "  " + elQuestion10 + "  ")
console.log( "1. **HTML qisqartmasi nima manosi va veb rivojlantirishda ularning bosh maqsadi nima?** " + elQuestion1)
console.log("HTML-da hiper havolani qanday yaratishingiz mumkin?" + elQuestion2)
console.log("CSS-da `margin` va `padding` orasidagi farqni izohlang." + elQuestion3)
console.log("HTML `<meta>` tegining maqsadi nima?" + elQuestion4)
console.log("CSS-da elementni horizontal ravishda qanday markazlashishingiz mumkin?" + elQuestion5)
console.log("Eng koʻp HTML elementlari uchun standart koʻrsatkich qanday va uni CSS-da qanday oʻzgartirishingiz mumkin?" + elQuestion6)
console.log(" CSS `float` xususiyatining maqsadi nima?" + elQuestion7)
console.log("HTML va CSS-da kodi qanday izohlang?" + elQuestion8)
console.log("HTML `<ul>` va `<ol>` elementlarining maqsadi nima?" + elQuestion9)
console.log("CSS box modelini va uning qismlarini izohlang." + elQuestion10)

